# For more info on Python, GitHub Actions, and Azure App Service
# please head to https://aka.ms/python-webapps-actions

name: Build and deploy Flask app to Azure App Service

on:
  push:
    branches:
      - main

env:
  WEBAPP_NAME: "smartbeef3" # Replace with the name of your Azure web app
  RESOURCE_GROUP: "DefaultResourceGroup-SEA" # Replace with the name of your Resource Group

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !node_modules/
            !venv/

  deploy-to-webapp:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Configure deployment and runtime settings on the webapp
        run: |
          az configure --defaults group=${{ env.RESOURCE_GROUP }} web=${{ env.WEBAPP_NAME }}

          az webapp config set \
            --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 app:app"
      #Deploy Lagi
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME}}
